node(label:'builder') {
  stage('preparation') {  
    git 'https://github.com/iimmssrepo/docker-demo.git'
  }
  stage('build') {
    def myTestContainer = docker.image('node:4.6')
    myTestContainer.pull()
    myTestContainer.inside {
      sh 'ls -la'
    }
  }
}